# Custom Language File for Launcher Customizer

[ejs.app]
title = "TheLastWorld"

[ejs.landing]
mediaGitHubURL = "https://github.com/riroute/TheLastWorld"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/mMDnDYgeP3"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE DANS THELASTWORLD"
welcomeDescription = "HUNTERZ STYLE"
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de TheLastWorld."
